version: 2

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201710-01
      docker_layer_caching: true
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run: yarn
      - run:
          name: Running E2E tests with JUnit reporter
          command: yarn cypress open
