version: 2

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201710-01
      docker_layer_caching: true
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run: .circleci/install-yarn.sh
      - run: source /opt/circleci/.nvm/nvm.sh && yarn
      - run:
          name: Running E2E
          command: source /opt/circleci/.nvm/nvm.sh && yarn cypress run
      - run:
          name: codechecks
          command: source /opt/circleci/.nvm/nvm.sh && yarn codechecks
